kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# define local registry

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://localhost:5000"]

nodes:
  - role: control-plane

