name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # downloads my repo code (like git clone+git checkout)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # installs docker builder

      - name: Build Docker image
        run: docker build -t my-fastapi:latest .  # building docker image (accroding my Dockerfile)

      # setup kind (local K8s, 'k8s in docker')
      - name: Setup kind
        uses: helm/kind-action@v1  
        with:
          version: v0.20.0
          cluster_name: kind

      # load image into kind
      - name: Load image into kind
        run: kind load docker-image my-fastapi:latest --name kind  # copies my docker image from the runner into kind's internal registry

      # Verify image loaded
      - name: Verify image in kind
        run: docker exec kind-control-plane crictl images | grep my-fastapi || echo "Image not found!"  # checking if the load image worked

      # Deploy to K8s
      - name: Deploy app
        run: kubectl apply -f deployment.yaml  # create 1 pod of my app

      # wait until the pod is in running state
      - name: Wait for pod
        run: |
          kubectl wait --for=condition=ready pod -l app=pr-demo --timeout=120s  

      # Check pod status
      - name: Check pod status  
        if: failure()  # if the previous step failed this shows me why
        run: |
          kubectl get pods -l app=pr-demo
          kubectl describe pods -l app=pr-demo
          kubectl logs -l app=pr-demo --tail=50

      - name: Run health check
        run: |
          POD_NAME=$(kubectl get pod -l app=pr-demo -o jsonpath="{.items[0].metadata.name}")
          kubectl port-forward $POD_NAME 8000:8000 &
          PF_PID=$!
          sleep 5
          curl --fail --retry 3 --retry-delay 2 http://localhost:8000/health || (kill $PF_PID && exit 1)
          kill $PF_PID

      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name kind || true